server:
  port: 8080
  servlet:
    context-path: /LibraryApplication
---
spring:
  profiles: local,default
datasource:
  appdata:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.HSQLDialect
---
spring:
  profiles: prod
datasource:
  appdata:
    url: jdbc:mysql://localhost:3306/libraryproject
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect